[package]
name = "testapp"
version = "0.1.0"
authors = ["transistor <trans@jabberwocky.ca>"]
edition = "2021"

[dependencies]
ruxpin_api = { path = "../../lib/ruxpin_api" }
ruxpin_app = { path = "../../lib/ruxpin_app" }
