[package]
name = "ruxpin"
version = "0.1.0"
authors = ["transistor <trans@jabberwocky.ca>"]
edition = "2021"

[features]
default = ["config-raspberrypi3"]
config-raspberrypi3 = ["arch-aarch64"]
arch-aarch64 = []

[dependencies]
ruxpin_api = { path = "../lib/ruxpin_api" }
