[package]
name = "sh"
version = "0.1.0"
authors = ["transistor <trans@jabberwocky.ca>"]
edition = "2021"

[dependencies]
ruxpin_api = { path = "../../lib/api" }
ruxpin_app = { path = "../../lib/app" }
ruxpin_types = { path = "../../lib/types" }

