[package]
name = "ruxpin_drivers_arm"
version = "0.1.0"
authors = ["transistor <trans@jabberwocky.ca>"]
edition = "2021"

[dependencies]
ruxpin_kernel = { path = "../../kernel" }
ruxpin_api = { path = "../../lib/api" }

